bind: 0.0.0.0
port: 8125
health_port: 8126
root: tmp/statsd
redis:
  host: 127.0.0.1
  port: 6379
retentions:
  10:  360 #1 hour
  60:  10080  #1 week
  600: 52594 #1 year
autotruncate: false
serializer: marshal
